# Generated by Django 5.1.4 on 2026-03-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='non_commence', max_length=20)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('termine_le', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Progression',
                'verbose_name_plural': 'Progressions',
            },
        ),
        migrations.CreateModel(
            name='UserQuizResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Meilleur score (%)')),
                ('nb_tentatives', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('passe', models.BooleanField(default=False, verbose_name='Quiz validé')),
                ('reponses', models.JSONField(blank=True, null=True, verbose_name='Dernières réponses')),
                ('premiere_tentative', models.DateTimeField(auto_now_add=True)),
                ('derniere_tentative', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Résultat de quiz',
                'verbose_name_plural': 'Résultats de quiz',
            },
        ),
        migrations.CreateModel(
            name='ChapitreDebloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debloque_le', models.DateTimeField(auto_now_add=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deblocages', to='courses.chapitre', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Chapitre débloqué',
                'verbose_name_plural': 'Chapitres débloqués',
            },
        ),
    ]
