# Generated by Django 5.1.4 on 2026-03-19 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitredebloque',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres_debloques', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AddField(
            model_name='userprogression',
            name='lecon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='courses.lecon', verbose_name='Leçon'),
        ),
        migrations.AddField(
            model_name='userprogression',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AddField(
            model_name='userquizresultat',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='courses.quiz', verbose_name='Quiz'),
        ),
        migrations.AddField(
            model_name='userquizresultat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_resultats', to=settings.AUTH_USER_MODEL, verbose_name='Élève'),
        ),
        migrations.AlterUniqueTogether(
            name='chapitredebloque',
            unique_together={('user', 'chapitre')},
        ),
        migrations.AlterUniqueTogether(
            name='userprogression',
            unique_together={('user', 'lecon')},
        ),
        migrations.AlterUniqueTogether(
            name='userquizresultat',
            unique_together={('user', 'quiz')},
        ),
    ]
