# Generated by Django 5.1.4 on 2026-03-21 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecon_video_fichier_lecon_video_youtube_url'),
        ('progress', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChapitreQuizResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, verbose_name='Meilleur score (%)')),
                ('nb_tentatives', models.PositiveIntegerField(default=0, verbose_name='Nombre de tentatives')),
                ('passe', models.BooleanField(default=False, verbose_name='Quiz chapitre validé')),
                ('reponses', models.JSONField(blank=True, null=True, verbose_name='Dernières réponses')),
                ('premiere_tentative', models.DateTimeField(auto_now_add=True)),
                ('derniere_tentative', models.DateTimeField(auto_now=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_resultats', to='courses.chapitre', verbose_name='Chapitre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitre_quiz_resultats', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Résultat quiz chapitre',
                'verbose_name_plural': 'Résultats quiz chapitres',
                'unique_together': {('user', 'chapitre')},
            },
        ),
    ]
