# Generated by Django 5.1.4 on 2026-03-21 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecon_video_fichier_lecon_video_youtube_url'),
        ('progress', '0003_chapitre_quiz_resultat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boite', models.PositiveSmallIntegerField(default=1, verbose_name='Boîte Leitner (1–5)')),
                ('prochaine_revision', models.DateField(verbose_name='Prochaine révision')),
                ('derniere_reponse_correcte', models.BooleanField(default=False)),
                ('nb_bonnes', models.PositiveIntegerField(default=0)),
                ('nb_total', models.PositiveIntegerField(default=0)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='courses.question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_historiques', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Historique question',
                'verbose_name_plural': 'Historiques questions',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
