# Generated by Django 5.1.4 on 2026-03-22 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_question_difficulte'),
        ('progress', '0004_user_question_historique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, max_length=2000, verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='courses.lecon', verbose_name='Leçon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='Élève')),
            ],
            options={
                'verbose_name': 'Note personnelle',
                'verbose_name_plural': 'Notes personnelles',
                'unique_together': {('user', 'lecon')},
            },
        ),
    ]
