# Generated by Django 5.1.4 on 2026-03-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('seconde', 'Seconde'), ('premiere', 'Première'), ('terminale', 'Terminale')], max_length=20, verbose_name='Niveau')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('score_minimum_deblocage', models.FloatField(default=60.0, help_text='Score moyen aux quiz requis pour débloquer le chapitre suivant.', verbose_name='Score minimum pour débloquer le suivant (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['matiere', 'niveau', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('physique', 'Physique'), ('chimie', 'Chimie'), ('mathematiques', 'Mathématiques')], max_length=50, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('contenu', models.TextField(help_text='Rédigez le cours en Markdown. Utilisez $...$ pour les équations LaTeX.', verbose_name='Contenu (Markdown)')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('duree_estimee', models.PositiveIntegerField(default=15, verbose_name='Durée estimée (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='courses.chapitre', verbose_name='Chapitre')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['chapitre', 'ordre'],
                'unique_together': {('chapitre', 'ordre')},
            },
        ),
        migrations.AddField(
            model_name='chapitre',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='courses.matiere', verbose_name='Matière'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre')),
                ('score_minimum', models.FloatField(default=60.0, verbose_name='Score minimum pour valider (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lecon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.lecon', verbose_name='Leçon')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Énoncé de la question')),
                ('type', models.CharField(choices=[('qcm', 'QCM (choix multiple)'), ('vrai_faux', 'Vrai / Faux')], default='qcm', max_length=20, verbose_name='Type')),
                ('options', models.JSONField(blank=True, help_text='Pour QCM : ["Option A", "Option B", "Option C", "Option D"]', null=True, verbose_name='Options de réponse')),
                ('reponse_correcte', models.CharField(help_text="Pour QCM : index 0-based (ex: 0, 1, 2...). Pour Vrai/Faux : 'vrai' ou 'faux'.", max_length=500, verbose_name='Réponse correcte')),
                ('explication', models.TextField(blank=True, verbose_name='Explication de la réponse')),
                ('points', models.PositiveIntegerField(default=1, verbose_name='Points')),
                ('ordre', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz', 'ordre'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapitre',
            unique_together={('matiere', 'niveau', 'ordre')},
        ),
    ]
