# Generated by Django 5.1.4 on 2026-03-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tolerances',
            field=models.JSONField(blank=True, help_text='Texte libre uniquement — liste de variantes acceptées : ["réponse alt 1", "réponse alt 2"]', null=True, verbose_name='Réponses alternatives acceptées'),
        ),
        migrations.AlterField(
            model_name='question',
            name='reponse_correcte',
            field=models.CharField(help_text="Pour QCM : index 0-based (ex: 0, 1, 2...). Pour Vrai/Faux : 'vrai' ou 'faux'. Pour Texte libre : la réponse attendue (insensible à la casse).", max_length=500, verbose_name='Réponse correcte'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('qcm', 'QCM (choix multiple)'), ('vrai_faux', 'Vrai / Faux'), ('texte_libre', 'Réponse texte libre')], default='qcm', max_length=20, verbose_name='Type'),
        ),
    ]
