# Generated by Django 5.1.4 on 2026-03-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_question_tolerances_alter_question_reponse_correcte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='video_fichier',
            field=models.FileField(blank=True, default='', help_text='Téléversez un fichier vidéo (MP4 recommandé). Ignoré si une URL YouTube est renseignée.', upload_to='lecons/videos/', verbose_name='Fichier vidéo'),
        ),
        migrations.AddField(
            model_name='lecon',
            name='video_youtube_url',
            field=models.URLField(blank=True, default='', help_text='Lien YouTube (ex: https://www.youtube.com/watch?v=... ou https://youtu.be/...)', verbose_name='URL YouTube'),
        ),
    ]
