# Generated by Django 5.1.4 on 2026-03-22 10:25
# Step 1 of 3: Add slug + gratuit fields WITHOUT unique constraints

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lecon_video_fichier_lecon_video_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='lecon',
            name='gratuit',
            field=models.BooleanField(default=False, verbose_name='Leçon gratuite (accessible sans compte)'),
        ),
        migrations.AddField(
            model_name='lecon',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, verbose_name='Slug'),
        ),
    ]
