# Generated by Django 5.1.4 on 2026-03-22 10:25

from django.db import migrations
from django.utils.text import slugify


def backfill_slugs_and_gratuit(apps, schema_editor):
    Matiere = apps.get_model("courses", "Matiere")
    Chapitre = apps.get_model("courses", "Chapitre")
    Lecon = apps.get_model("courses", "Lecon")

    # Matiere slugs (nom is already slug-safe)
    for m in Matiere.objects.filter(slug=""):
        m.slug = m.nom
        m.save(update_fields=["slug"])

    # Chapitre slugs — deduplicate within (matiere, niveau)
    for ch in Chapitre.objects.filter(slug="").select_related("matiere"):
        base = slugify(ch.titre)[:255] or f"chapitre-{ch.pk}"
        slug = base
        counter = 2
        while Chapitre.objects.filter(
            matiere=ch.matiere, niveau=ch.niveau, slug=slug
        ).exclude(pk=ch.pk).exists():
            slug = f"{base[:250]}-{counter}"
            counter += 1
        ch.slug = slug
        ch.save(update_fields=["slug"])

    # Lecon slugs — deduplicate within chapitre
    for l in Lecon.objects.filter(slug="").select_related("chapitre"):
        base = slugify(l.titre)[:255] or f"lecon-{l.pk}"
        slug = base
        counter = 2
        while Lecon.objects.filter(
            chapitre=l.chapitre, slug=slug
        ).exclude(pk=l.pk).exists():
            slug = f"{base[:250]}-{counter}"
            counter += 1
        l.slug = slug
        l.save(update_fields=["slug"])

    # Mark first lesson (ordre == 1) of each chapter as free
    Lecon.objects.filter(ordre=1).update(gratuit=True)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_chapitre_unique_together_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_slugs_and_gratuit, migrations.RunPython.noop),
    ]
