# Generated by Django 5.1.4 on 2026-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_slug_unique_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulte',
            field=models.CharField(choices=[('facile', 'Facile'), ('moyen', 'Moyen'), ('difficile', 'Difficile')], default='moyen', max_length=20, verbose_name='Difficulté'),
        ),
    ]
