# Generated by Django 5.1.4 on 2026-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse email')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('eleve', 'Élève')], default='eleve', max_length=10, verbose_name='Rôle')),
                ('niveau', models.CharField(blank=True, choices=[('seconde', 'Seconde'), ('premiere', 'Première'), ('terminale', 'Terminale')], max_length=20, null=True, verbose_name='Niveau')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès admin Django')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
