# Generated by Django 5.1.4 on 2026-04-01 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_connexionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(max_length=255, verbose_name='Stripe Customer ID')),
                ('stripe_subscription_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Subscription ID')),
                ('plan', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=20, verbose_name='Plan')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('annule', 'Annulé'), ('expire', 'Expiré')], default='actif', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'indexes': [models.Index(fields=['user', 'statut'], name='users_abonn_user_id_39abc9_idx')],
            },
        ),
    ]
