# Generated by Django 5.1.4 on 2026-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_beta',
            field=models.BooleanField(default=False, verbose_name='Bêta-testeur'),
        ),
    ]
